### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Gamekiller48** [SesuMoe/sd-tagger-webui#6]
When trying to use this extension, I receive an error message when entering the dataset path:

![tagger_error](https://user-images.githubusercontent.com/8791838/216781900-92317932-4e8e-4623-abb5-3e9fa0d71517.PNG)

Webui is running version commit hash: 3e0f9a75438fa815429b5530261bcf7d80f3f101

**Comment by SesuMoe** [comment]
Hi, thanks for posting and sorry for the late response.

This issue should be resolved with latest commits to main.
