### ISSUE TITLE
Bugs and needed features

### ISSUE THREAD

**Issue by dasparadoxon** [SesuMoe/sd-tagger-webui#7]
first : this is exactly what I need for my workflow, thank you for doing that. I forked it and will try to work on it.

bugs : 

- not compatible with new default dark theme
- when using current image slider the tags of current image are not saved

features I need and will try to implement in my fork :

- add new Tag
- default tag set
- tag categories
- optional saving and loading tags from database
- sort tags alphabetically
- show tag use count for current dataset
- showing on the tag button which tag button allready has been 
  added (optional hide that tag for current image)
- autocomplete for tags in tags box
- clear tag search box button

**Comment by SesuMoe** [comment]
Hi, thanks for writing. I appreciate that you found it useful- as did I! Sadly with the updates to gradio and my lack of interest in stable diffusion I didn't feel up to fixing it.

Just a couple of things,
I'm completely open to contributions if you wanted to help keep the project moving forward. As for your features, I actually did implement some of them.

- For sort tags alphabetically 
![image](https://github.com/SesuMoe/sd-tagger-webui/assets/96925462/ef786b27-ead8-4556-b412-b476c462503f)
- Autocomplete for tags in tags box - I had made a hook using this extension: https://github.com/DominikDoom/a1111-sd-webui-tagcomplete which allowed me to do essentially this, although it had issues.
- Clear tag search box button - I think this was implemented, but never actually included.

The other features sound interesting, but might take sometime. Either way, I appreciate your work and good luck!
